version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3-node
        environment:
          PGHOST: localhost
          PGUSER: crew
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: crew
          POSTGRES_DB: crew_test
          POSTGRES_PASSWORD: ""
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler -v $(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - crew-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - run: bundle clean --force
      - save_cache:
          paths:
            - vendor/bundle
          key: crew-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v2-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v2-{{ checksum "yarn.lock" }}
          paths:
            - 'node_modules'

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: bundle exec rails db:schema:load
      - run: bundle exec rails test
